README.md
app/app.js

We were using the word `format` but in Puppeteer that's for determining print dimensions (A4, A5, etc).

SNAP-6: use output param to control output filetype

---

app/app.js

Adds a paginated footer to generated PDFs.

SNAP-17: paginated footer on PDFs

---

app/app.js

SNAP-14: display URL in PDF footer

---

README.md
app/app.js
app/package-lock.json
app/package.json

PR adds sanitization and validation to the user input. I picked some criteria based on either what I'm working with on our downstream projects, or what I thought made sense. Might need to be changed later.
When we detect bad input, the service responds with **HTTP 422, Unprocessable Entity** and JSON containing a reason for the validation failure. Two examples:
```js
// width has 'px' unit appended
{
"errors": [
{
"location": "query",
"param": "width",
"value": "768px",
"msg": "Must be an integer with no units"
}
]
}
```
```js
// output format is not one of the specific values available
{
"errors": [
{
"location": "query",
"param": "output",
"value": "jpeg",
"msg": "Must be one of the following: png, pdf"
}
]
}
```

SNAP-10: input sanitization

---

README.md

People won't know what this service does without a proper intro.

Important Update™ to README

---

app/package-lock.json
app/package.json

OPS-5262: upgrade to nodemon@1.18.7

---

app/app.js

Design tweaks for DSR-specific hardcoded header/footer.

DSR-83: design tweaks for PDF header/footer

---

README.md
app/app.js

- https://humanitarian.atlassian.net/browse/SNAP-20
@emmajane at least one review is required so I am setting you and giving you the authority to either assign someone else who is available or hit the button.

Production Deploy 2018-12-17

---

app/app.js

I let the US-style date slip through, needs to follow UN format in all languages.

SNAP-23: follow-up to standardize on UN date format

---

README.md
app/app.js

[SNAP-36] log all the things

---

app/app.js

typo in PNG generation logging

PNGs were too cheesy

---

README.md
app/app.js
app/locales/en.js
app/locales/fr.js

"Date of Creation" => Downloaded

PDF Footer wording

---

README.md
app/app.js

Add a flag that lets people request Landscape PDFs.

SNAP-32: allow option to generate Landscape PDFs

---

app/app.js

I forgot to log the new stuff.

log new params in ELK

---

README.md
app/app.js
app/package.json

I think I got this working without any disruption to existing functionality. There were a couple silly errors that were preventing use and I tracked them down without too much trouble.
README got a slight re-org to accommodate our essential input versus optional parameters.
I used all my pre-existing Insomnia requests to test this against prod URLs, and everything seemed to check out! However, I'm still requesting breakage from my Partner in Print. 👀

SNAP-44: HTML input

---

README.md
app/app.js

You can fill in whatever you want that suits your project, but we're calling it UA.

SNAP-47: log the User-Agent

---

README.md
app/app.js

Reverts UN-OCHA/tools-snap-service#49
Gonna go with a Header instead of this approach.

Revert "SNAP-47: log the User-Agent"

---

app/app.js

See related puppeteer issue: https://github.com/GoogleChrome/puppeteer/issues/728

OPS-5361 - wait for external resources to be loaded

---

README.md
app/app.js

I didn't mean to make Chris' work be not in altogether, the header and the param should be able to place nice.

[SNAP-47] Log the user-agent

---

app/app.js

Puppeteer's `elementHandle.screenshot()` is allegedly aliased to `page.screenshot()` with the `clip` option populated. However in practice they were producing different results, so we're manually setting the `clip` property with the results from `elementHandle.boundingBox()` after fetching the desired selector.

SNAP-51: manually clip selector-based PNGs

---

README.md
app/app.js

- SNAP-51: manually clip PNG Snaps

Clip PNGs manually

---

app/package.json

bump package.json so it matches our next release

---

README.md
app/app.js

HID-1790: also allow hyphens in requesting service

---

README.md
app/app.js
app/package.json

Errors and Underscores

---

app/package-lock.json
app/package.json

Keeping up to date

---

Dockerfile
app/app.js
app/package-lock.json
app/package.json

This will probably need follow-up fixes to the various node packages (and at least a puppeteer bump) by @rupl

[OPS-6013] Bump base image to chrome 80 and node 12.13.

---

Dockerfile
app/package-lock.json
app/package.json

Note this *also* bumps chrome from v80 to v81.

[SNAP-64] Bump the base image version so that /bin/ps is present for the health check.

---

app/package-lock.json
app/package.json

OPS-6350: update deps

---

app/app.js
app/package-lock.json
app/package.json

Adding a health check so pingdom can monitor.

SNAP-66: health check

---

Dockerfile
app/package.json

Update Puppeteer version to match stable release.
I couldn't figure out how to request changes outside the diff in the PR so here's a PR for your PR.

OPS-6013: use Chrome stable

---

app/package-lock.json
app/package.json

SNAP-68: dependency bumps

---

Dockerfile
app/app.js
app/package-lock.json
app/package.json

Our release scheduled for Thursday, June 25.

Production Release 2020-06-25

---

app/package.json

Bumping puppeteer/Chrome to latest stable.

SNAP-70: Chrome stable 2020-08

---

app/package-lock.json
app/package.json

SNAP-70: Chrome 84 stable

---

README.md

- Added a ToC
- Linked to drupal module
- Linkable parameters, added table to display info about param: defaults/required/type 
- Made a note about RWD assumption inside `width` param (most likely to be affected)

SNAP-71: big ol' docs update

---

app/app.js
app/package-lock.json
app/package.json

cc @cafuego 
This PR will definitely be easier to review with [whitespace disabled](https://github.com/UN-OCHA/tools-snap-service/pull/92/files?diff=unified&w=1) (had to wrap a big block of code so lots of re-indentation).
(also `package-lock.json` wasn't up to date, so i did that too in a separate commit before my changes).

OPS-6963: Limit the max number of concurrent requests to puppeteer.

---

app/package-lock.json
app/package.json

SNAP-77: bump Chrome/puppeteer

---

app/package-lock.json
app/package.json

Bumping our Chrome/puppeteer. Details in JIRA ticket.

SNAP-81: bump Chrome/puppeteer

---

README.md
app/app.js

We didn't make it clear how this works for local dev. This at least gives us a place to 👉

SNAP-81: readme for allowlist + change error

---

app/app.js
app/package-lock.json
app/package.json

- Chromium `88.0.4324.182-1` (stable)
- `puppeteer@8.0.0`
- `pm2@4.5.5`
- `mkdirp@0.5.5`

SNAP-86: monthly maintenance

---

Dockerfile
README.md
app/app.js
app/package-lock.json
app/package.json

- SNAP-81: some docs for our allow-list
- SNAP-86: monthly Chrome bump for Feb 2021
- OPS-7296: use generic node.js builder image
- security patches

Production 2021-03-04

---

app/app.js
app/package-lock.json
app/package.json

- SNAP-88: downgrade puppeteer from 8.0.0 to 6.0.0

Production 2021-03-04 without breaking changes

---

app/package-lock.json
app/package.json

Monthly Chromium bump, puppeteer to 8.0.0, pm2 updated.

SNAP-90: monthly updates

---

app/app.js
app/package-lock.json
app/package.json

- Monthly Chromium update
- puppeteer@8.0.0
- pm2@4.5.6

Production 2021-04-15

---

app/app.js
app/package-lock.json
app/package.json

- SNAP-90: log UA so I can be double sure what we're running by checking Kibana
- Chromium `90.0.4430.72-1`
- UA: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/90.0.4430.72 Safari/537.36`

Production follow-up

---

.travis.yml
README.md
app/.eslintrc.js
app/.eslintrc.json
app/app.js
app/package-lock.json
app/package.json

[SNAP-57] lint the codebase on Travis

---

Dockerfile
app/package-lock.json
app/package.json

I merged #135 into this branch so we can test it all in one go. FYI @teodorescuserban

[SNAP-96] Regular Chromium updates 2021-08

---

app/package-lock.json
app/package.json

Regular updates to Chromium, plus some npm dependency updates as well.

SNAP-99: monthly Chromium updates

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Monthly updates to our dependencies. No breaking changes for Snap users.
We're using the CHANGELOG generator and it will live inside the `app` directory with the rest of the codebase.

SNAP-100: monthly Chromium/dependency updates

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Add CHANGELOG and bump version

---

CONTRIBUTING.md
app/CHANGELOG.md
app/package-lock.json
app/package.json

Regularly scheduled security updates. See details in ticket.

SNAP-101: monthly Chromium/dependency updates

---

Dockerfile
app/package-lock.json
app/package.json

[SNAP-105]
Bumping from v12 to v16 as suggested in the ticket. Builds okay locally.
[SNAP-105]: https://humanitarian.atlassian.net/browse/SNAP-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SNAP-105] update nodejs

---

CONTRIBUTING.md

The docs were somewhat inadequate during yesterday's release prep, so I updated them to be more thorough.

[SNAP-108] maintainer docs

---

CONTRIBUTING.md
app/CHANGELOG.md
app/package-lock.json
app/package.json

Standard security updates to Chromium/Puppeteer and also app dependencies.

[SNAP-110] monthly Chromium/Puppeteer updates

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

* all boolean params accept case-insensitive strings ([d623b14](https://github.com/UN-OCHA/tools-snap-service/commit/d623b1405ee8116d10da6f746954fa8d6e76903a))
* **security:** update Chromium/puppeteer ([a06d07e](https://github.com/UN-OCHA/tools-snap-service/commit/a06d07e4e065068315dc0c23f893a56e1f804b89))

Prepping v3.0.4

---

app/.eslintrc.js
app/CHANGELOG.md
app/app.js

Removed deprecated code, then had to figure out how to lint it.

Prepping 3.0.4 trying again

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Production 2022-11-24

---

.github/workflows/checks.yml

PR to see what happens on GitHub.

test: try to use node 16 in GitHub Action

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Monthly security updates to Chromium/Puppeteer, plus release notes.

[SNAP-120] monthly updates

---

.github/workflows/checks.yml
app/CHANGELOG.md
app/package-lock.json
app/package.json

Bump puppeteer. Local npm audit was clean.

Release 2023-03-30

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

This includes both puppeteer and release notes: all-in-one PR!

[SNAP-122] Monthly updates

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Update puppeteer, end scene! 🎭

[SNAP-123] Monthly upgrades 2023-06

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Prepping latest release with Chromium/Puppeteer bumps.

[SNAP-124] monthly updates

---

app/package-lock.json

chore(deps): upgrade semver

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Contains updates to node.js, Chromium, Puppeteer

Release 2023 10 17

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

[Fresh deps!](https://www.youtube.com/watch?v=fhdCslFcKFU)

Release 20231023

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

fix(security): update Chromium/puppeteer

---

app/package-lock.json
app/package.json

This is my first build for snap, so fingers crossed nothing breaks.
Refs: SNAP-135

chore: Update all the things, but specifically puppeteer (and thus chrome)

---

CONTRIBUTING.md
Dockerfile
app/package-lock.json
app/package.json

* nodejs v22
* Newer pm2 and ws versions
* New puppeteer version
Refs: OPS-10552

chore: Version bump.

---

app/package-lock.json
app/package.json

chore: Hey! New pupetteer to match the current Chrome!

---

app/package-lock.json
app/package.json

chore: Bump time!

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

chore: Monthly update, including security fixes.

---

app/package-lock.json
app/package.json

chore: Bump puppeteer to v24.2.0 which matches the current Chrome (133).

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

chore(release):  Bump puppeteer to v24.4.0 which matches the current Chrome 134)

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

chore: Bump chrome and puppeteer.

---

app/app.js
app/package-lock.json
app/package.json

chore: Remove the apm module, as we do not use it. At all.

---

README.md
app/app.js
app/package-lock.json
app/package.json

Refactor a little bit to allow output to be used as a type option in the screenshot call. Default to PDF.
Refs: SNAP-49

feat: Add new screenshot image types.

---

app/CHANGELOG.md
app/package-lock.json
app/package.json

Puppeteer 24.10.0
Chrome 137.0.7151.68
Refs: OPS-11581

fix(security): Update Puppeteer and Chrome.
