UN-OCHA/tools-snap-service

- README.md
- app/app.js
Allow CSS Media to be set to either `screen` (default) or `print`. This is the media only, not a media query such as `(min-width: 768px)`.
> SNAP-5: emulate CSS Media (screen|print)

- README.md
- app/app.js
Set viewport width/height when generating a snap. For DOM fragment Snaps this is particularly useful to ensure that the user receives exactly what they saw on their screen.
> SNAP-7: viewport dimensions

- app/app.js
Follow-up to #4 — I tried setting a unit in my parameter and the thing just errored out with no advice on why. Maybe in the future we could provide more structured response codes but for now it at least gives you a reason in the response.
> SNAP-7: show something useful when sending 500

- README.md
- app/app.js
PR allows the device pixel density to be set, and the new default is `2` instead of `1` — this produces "retina" screenshots by default which is the conservative action, allowing people to downsample if necessary. Can't add resolution after the fact and people will want to share sharp, beautiful graphics.
> SNAP-9: allow pixel density to be set for Snaps

- README.md
- app/app.js
- app/package-lock.json
- app/package.json
Three new parameters to allow for custom Header text. Instead of accepting HTML/CSS we are opting for specific parameters that we can more tightly sanitize and style.
Full range of ASCII characters are considered valid input. This allows stuff like colons, dashes, and other common punctuation. We sanitize before printing to avoid arbitrary HTML or inline JS being injected.
Examples:
- What it should look like: [snap-15-normal.pdf](https://github.com/UN-OCHA/tools-snap-service/files/2501092/snap-15-normal.pdf)
- What a malicious request would look like: [snap-15-malicious.pdf](https://github.com/UN-OCHA/tools-snap-service/files/2501090/snap-15-malicious.pdf) (subtitle contains `<script>` which isn't executed because it was escaped)
> SNAP-15: custom header text

- README.md
- app/app.js
Optional footer text. Replaces the hardcoded URL from before, since any website can send their own URL as the footer text.
Example: [SNAP-16-footer-text.pdf](https://github.com/UN-OCHA/tools-snap-service/files/2528837/SNAP-16-footer-text.pdf)
> SNAP-16: optional custom footer text

- README.md
- app/app.js
This PR introduces the ability to make more than one simultaneous request. While not perfect, it seems to work for N-1 simultaneous requests. That suggests to me that the issue lies somewhere in the code I wrote, not in the dependencies.
To sum up the changes using a desktop computer as an analogy, before the PR we were effectively launching a new Chrome each time a Snap was requested, and now we're just opening a new incognito tab each time a Snap comes in.
At any rate, I moved the init code to a function. When it runs the first time, the Puppeteer API outputs a connection string, and any subsequent run will reuse that connection. Then, down where we used to have initialization, we open a "context" which is a sandboxed session. I used millisecond timestamp plus the querystring to create …
> OPS-5130: multiple requests don't crash process

- app/app.js
I believe this does the trick! Ran a bunch of snaps and instead of an ever-increasing pile, I get just three seemingly permanent processes for Chrome:
- `--type=zygote`
- `--type=gpu-process`
- `--type=renderer`
I believe the `renderer` process is a dormant "tab" which _maayyybe_ is a consequence of initiating the Chromium connection itself? Not sure. But I was able to see all the other `renderer` processes appearing and disappearing with the code in PR as Snaps get created and finish executing.
I manually ran about five at a time and never had any crash. It seems able to handle the same load as before, at least according to my very unscientific testing.
> SNAP-31: release resources

- app/app.js
I was too strictly validating some string input that ended up preventing French PDFs from being generated. My original motivation for restricting letters was to avoid XSS. So, instead of expanding the valid charsets we accept, I removed the validation entirely and replaced with HTML sanitization.
Here's a fun-looking PDF that doesn't `alert('hello')`
[SNAP-29-no-xss-jp-zh-fr.pdf](https://github.com/UN-OCHA/tools-snap-service/files/2668221/SNAP-29-no-xss-jp-zh-fr.pdf)
> SNAP-29: remove validation and sanitize HTML instead

- README.md
- app/app.js
This PR grants requesting services the ability to send the browser cookies along in order to retain personalization (such as chosen language) or session authentication. Cookies are totally optional.
I assume for legacy reasons related to either Netscape or IE6, that cookies are surprisingly uniform in their format across the various platforms and browsers. Every browser which we offer even basic support for conforms to the rather specific format I'm looking for in the code. If there was ever a problem I'm sure we can leverage some cookie parser, but it seems to be pretty standard format (cookies separated by semi+space):
```
name=value; another=value; third=value
```
For the record I checked:
- Win7 / IE11
- Win10 / Edge 18
- macOS 10.14.1 Safari
- macOS Chrome 72
- macOS Firefox 63
I …
> SNAP-20: set browser cookies when available

- README.md
- app/app.js
- app/locales/_list.json
- app/locales/en.js
- app/locales/fr.js
Makes the changes necessary to localize the PDF footer. The header is powered by open-ended text input and the requesting service is responsible for providing whatever localized text it wants.
However, the pagination and creation date are supplied by Snap Service and required different treatment. If there is a language that doesn't match the current setup, we'll revisit. But the languages we have on hand work with a pretty minimal PR.
> SNAP-23: optionally localize PDF footer

- README.md
- app/app.js
Puppeteer avoids printing CSS related to `background-*` by default. It can be enabled with one param and this PR allows folks to use it.
I noticed I had incorrectly implemented the Boolean for `pdfLandscape` and the fix is in this branch.
> SNAP-41: support Puppeteer printBackground param

- app/app.js
Came across this while testing HR.info Snaps. I was setting cookies even when there were no cookies to set.
> don't set cookies if there aren't cookies

- README.md
- app/app.js
A validation error *must* return HTTP status 422, or the keepalived check script will detect the service as down.
I think this is better than simply throwing a 400, for the same reasons that lead us to choose 422 originally for validation errors on optional parameters. But if need be, I can modify the check script to accept `400 <= status < 500` as "up" instead.
> [SNAP-44] Error out if html and url are both present or both absent

- README.md
- app/app.js
- app/package-lock.json
- app/package.json
Debugging tools that were developed to facilitate the completion of the HDX integration:
* `delay` lets you specify up to 10000 milliseconds of additional delay. For times when `page.onload` still isn't enough (lazy-loaded images and whatnot)
* `debug` will dump errors, warnings, and info from the JS console into ELK, so you can see what a problematic webpage is doing when Snap loads it.
* `block` will accept a comma-separated list of domains, and Snap will block any domain which contains any of the strings. It's greedy on purpose. When a domain is blocked, the `debug` property of the ELK logs will report as such.
> SNAP-42: debugging tools

- app/app.js
Remove DSR-specific code. We're now explicitly setting: https://github.com/UN-OCHA/reports-site/pull/246
> SNAP-54: remove magic DSR number from pdfHeader+logo scenario

- Dockerfile
- app/package-lock.json
- app/package.json
- docker-compose.yml
Uses https://github.com/UN-OCHA/docker-images/pull/208
~~Note that app/app.js will need modification so it spawns the puppeteer-installed chrome version. There is no google-chrome binary at /usr/bin anymore.~~
> [OPS-5771] snap base work

- app/app.js
- app/package-lock.json
- app/package.json
We once had troubles with screenshots directly on fragments so we switched to a manual method. The manual method is now the buggy method so we're switching back.
The code for the manual method is still there but commented out for the next time this happens.
> SNAP-51: revert to ElementHandle method of PNG+selector screenshots

- Dockerfile
- app/app.js
See https://github.com/UN-OCHA/docker-images/pull/224
> [OPS-6072] Bump the base image (and builder) to the one with the Noto fonts.

- app/package-lock.json
- app/package.json
Bumping puppeteer to match this month's stable Chrome release.
> SNAP-67: update puppeteer for current stable Chrome 2020-06

- app/app.js
- app/package.json
It turns out the "invalid_url" error is due to https://github.com/validatorjs/validator.js trying to be nice to Internet Explorer and cutting strings to 2083 chars.
This is used by https://github.com/express-validator/express-validator used by snap to check the validity of URLs.
This PR is overloading isUrl method of express-validator with the validate_length param (which eventually gets to the validator.js isUrl method).
Thanks to @aalecs for help.
```validate_length - if set as false isURL will skip string length validation (2083 characters is IE max URL length).```
> [SNAP-42] Migrate HDX to shard snap service

- app/app.js
- app/package-lock.json
- app/package.json
Refuse to snap if the host is not listed.
```
docker-compose.yml:
environment:
- MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-2}
- ALLOWED_HOSTNAMES=localhost,www.google.com
cafuego@calvados:~/Development/unocha/tools-snap-service (cafuego/ops-7153-snap-safety *$)
; curl -XPOST http://127.0.0.1:8442/snap?url=https://www.disney.com
{"errors":[{"location":"query","param":"url.hostname","value":"www.disney.com","msg":"The supplied `url` is not on the list of allowed hostnames."}]}
cafuego@calvados:~/Development/unocha/tools-snap-service (cafuego/ops-7153-snap-safety *$)
; curl -XPOST http://127.0.0.1:8442/snap?url=https://www.google.com
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output …
```
> [OPS-7153] Check a passed url against a list of permitted hostnames.

- Dockerfile
NodeJS at 12.20.1
Buster up to date. It still seems to include `google-chrome-unstable`. I thought we removed it from the package list because not being used and to minimize the image size?
> [OPS-7237] use the latest security patched base image

- app/app.js
- app/package-lock.json
- app/package.json
This is a downgrade of puppeteer from 8.0.0 to 6.0.0 in order to avoid breaking changes that affected at least one team during our dev testing period.
> SNAP-88: downgrade puppeteer to 6.0.0 to stave off the breaking change

- app/app.js
- app/package.json
Our deploy went poorly and we have to rebuild the image. While doing so I thought why not make this local log statement permanent, so that we can easily see in Kibana what Chromium we're connecting to (if any).
> SNAP-90: log UA into ELK when connecting to Chromium

- app/app.js
- app/package-lock.json
- app/package.json
Trying to produce more errors during startup in order to help debug our prod-only failures from the last two weeks. I did small cleanups to also hide any 500s from the end-user themselves, and used the conventions from HID to standardize some logging fields. Not sure if they have to be added to Kibana indexer but the new fields are:
```js
{
fail: true, // Boolean
stack_trace: "", // String
}
```
Tagging @cafuego for eventual review, but merging in order to tag while the Chrome stable download is identical/similar to the package I downloaded while building+testing locally.
> SNAP-90: more error handling

- app/app.js
- app/package-lock.json
- app/package.json
Another attempt to debug our mysterious prod-only outage. See #120 for a few more details.
- Snap UA: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/90.0.4430.85 Safari/537.36`
- Chromium: `90.0.4430.85-1`
- puppeteer: `8.0.0`
> SNAP-90 deployment followup

- .dockerignore
- Dockerfile
The base image is now also more up to date and no longer contains chrome
(stable or unstable) so it all gets a bit smaller, neater and faster to
build, push and pull.
See https://github.com/UN-OCHA/docker-images/pull/272
> [SNAP-90] Do not try to re-add the repo, as the base image already configures it.

- app/package-lock.json
- app/package.json
Monthly updates:
- Chromium 91.0.4472.77-1
- UA: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/91.0.4472.77 Safari/537.36","time":"2021-05-31T08:36:27.039Z`
- Puppeteer 9.0.0
> [SNAP-91] monthly Chrome bump

- app/package-lock.json
- app/package.json
Version bump, nothing else. See #127 for code changes.
Our troubles in the previous month required multiple bumps and the codebase got out of sync with docker image tags.
> [SNAP-91] second version bump

- app/package-lock.json
- app/package.json
Doing some security work ahead of time so @lazysoundsystem isn't left with dirty work during my holiday 😁 
`pm2` got a major update but perusing their changelog it wasn't explicit in what broke. However 5.1.0 got rapidly released which claims to restore node.js@10 support, so I think that was the breaking change. We're on 12 so all good.
> [SNAP-94] node deps

- README.md
- app/app.js
This has always been our policy in our docs but now the response is very clear about it being an intentional design.
I also forgot to update docs in #158 so this branch includes docs for both PRs.
> SNAP-50: return HTTP 405 for any GET request to /snap

- app/CHANGELOG.md
- app/package-lock.json
- app/package.json
Upgrades puppeteer to match latest stable Chromium, and includes release notes for this week's deploy.
> SNAP-103: upgrade Chromium and prepare release

- app/package.json
Since we manage the tags via GitHub Releases, we don't want our command-line tool to make tags for us.
> [SNAP-106] ensure future releases skip creation of git tag

- CONTRIBUTING.md
Re-ordering the steps removes the possibility that out of date branches get tagged, and also eliminates the need to merge main/master back into dev to achieve correct outcomes when generating CHANGELOG updates.
I also noticed that by copying from CD I'd left some branch names in there that don't exist.
> [SNAP-108] further improve maintainer docs for creating releases

- app/app.js
- app/package-lock.json
- app/package.json
This should allow PHP to send its all-caps booleans to Snap without anything breaking.
> [SNAP-112] all boolean params accept case-insensitive strings

- README.md
- app/app.js
We weren't catching this at all before, but now it returns a JSON-formatted 400 with an explanation.
Refs: SNAP-117
> fix: return explicit 400 for invalid URLs

- .github/workflows/checks.yml
- Dockerfile
Refs: OPS-9554
A minimum of changes, to beat the node16 EOL date.
> chore: upgrade to node20

- app/CHANGELOG.md
- app/app.js
- app/package-lock.json
- app/package.json
- Standard updates to Chromium/Puppeteer
- Security updates to dependencies
- Upgrading `elastic-apm-node` to a new version so that its `engines` requirements are met. The old version only went up to node 19 and this branch puts us on 20.
- Opt-in to `headless: "new"` mode, which isn't yet the default, but will be "in the future"
> [SNAP-125][SNAP-126] Periodic updates

- app/CHANGELOG.md
- app/package-lock.json
- app/package.json
* **security:** update Chromium/puppeteer
> chore(release): 3.2.9

- README.md
- app/app.js
If a timeout is detected, we now throw a 502 and attempt to close the browser tab/connection afterwards.
To test this, I added `sleep(61)` to a local Drupal index.php and Snap seemed to respond in kind as I comment/uncomment the line of code.
I had to re-indent a huge block of code to add the try/catch/finally, so the GitHub UI option to eliminate whitespace changes might be useful to review. It's a small change otherwise.
> [OPS-10018] Handle timeouts better

- CONTRIBUTING.md
- app/CHANGELOG.md
- app/app.js
- app/package-lock.json
- app/package.json
A bit more exciting than usual because one breaking change actually affected us. We were using `browser.createIncognitoBrowserContext()` and it got renamed to `browser.createBrowserContext`. They renamed because the isolation is fundamental to new contexts, meaning all cookies and localStorage are isolated even amongst concurrent Snaps. I noted the change in the comments, but here are some receipts just the same:
- https://github.com/puppeteer/puppeteer/blob/puppeteer-v22.0.0/docs/api/puppeteer.browsercontext.md#browsercontext-class
It took me some time to track the breaking change down because it wasn't listed under [Puppeteer v22.0.0](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v22.0.0) rather under the sub-project in the same repo [puppeteer-core …
> [SNAP-133] monthly updates to Chromium/Puppeteer

- README.md
- app/app.js
BREAKING CHANGE: our docs have always said the service parameter is required, but in code it was optional until now. It is now truly required.
Refs: SNAP-76
> [SNAP-76] enforce required service param

- app/CHANGELOG.md
- app/package-lock.json
- app/package.json
* `service` parameter is now required for all requests to `/snap` - SNAP-76
* Maintain the puppeteeer browser path override, so we can run with chromium or firefox on ARM hardware ([9a73862](https://github.com/UN-OCHA/tools-snap-service/commit/9a73862c374aa6fea44dc6938675248dd2545bdd))
* catch Chromium timeout errors too ([1187075](https://github.com/UN-OCHA/tools-snap-service/commit/11870759e13c17a3d6a2d7a6e4b0a98d92b66121))
* enforce required service param ([0521944](https://github.com/UN-OCHA/tools-snap-service/commit/05219442e3b164274529cd87f413328dbce5439a))
* **security:** update Chromium/puppeteer ([b277343](https://github.com/UN-OCHA/tools-snap-service/commit/b2773433b962ab526b931212900e7a2d70a17c6f))
> Release 2024-04-11

- .github/workflows/build.yml
- .github/workflows/checks.yml
> chore: Bump the actions used to current versions, so they are on a supported node version.

- CONTRIBUTING.md
- Dockerfile
- app/CHANGELOG.md
- app/package-lock.json
- app/package.json
Includes:
* A new node22 base image.
* A new pm2 version.
* An updated puppeteer version.
* An updated chrome version.
> security: Prep for a new release with a security fix for pm2.

- app/app.js
This allows the client to handle this specific error as its own thing, not as a generic backend error.
Refs: SNAP-93
> feat: Return error 400 when the specified selector is not found.
